/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.testrabbitmq.send;

import org.junit.Test;

import com.testrabbitmq.send.Send;

import static org.junit.Assert.*;

public class SendTest {
    @Test public void testSomeLibraryMethod() {
    	Send classUnderTest = new Send();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someSendMethod());
    }
}
